# Generated by Django 3.2.6 on 2021-08-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course_id', models.IntegerField()),
                ('instructor_name', models.CharField(max_length=50)),
                ('duration', models.DecimalField(decimal_places=1, default=0.0, max_digits=1000)),
            ],
        ),
    ]
